can configuration for rf transmission
PGRacing/TelemetryGrafana pull request #2
Opened 2024-08-21 13:58 UTC by MalwinaKozak

2024-08-21 13:59 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "name": "lambda",
same name as previous

2024-08-21 14:31 UTC, cepekLP requested changes

2024-08-21 14:31 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +            "IGNANG":
change name to ignition angle

2024-08-21 14:31 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "name": "DWELL",
change name

2024-08-21 14:31 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "name": "fps",
change name to fuel_pump_state

2024-08-21 14:31 UTC, cepekLP commented on code/data_filtration.py
> +        distance_km = radius_earth_km * c
add function to calculate distance from longitude nad latitude delta

2024-08-21 14:31 UTC, cepekLP commented on code/data_filtration.py
> +            for i in range(3):
why to for functions?

2024-08-21 14:31 UTC, cepekLP commented on code/func_abs.py
> +def vss_data_live(data_bytes, prev_speed, if_front):
better would be is_front

2024-08-21 14:31 UTC, cepekLP commented on code/func_abs.py
> +            if_front = 'front'
better would be axle

2024-08-21 14:31 UTC, cepekLP commented on code/func_abs.py
> +    flow_multiplier = 32.
flow?

2024-08-21 14:31 UTC, cepekLP commented on code/func_ecumaster.py
> +LIve telemetry.
```suggestion
Live telemetry.
```

2024-09-03 12:00 UTC, cepekLP requested changes

2024-09-04 08:59 UTC, cepekLP requested changes

2024-09-04 08:59 UTC, cepekLP commented on code/func_gps.py
> +        lat = (float(lat) / 100 // 1) + (float(lat) % 100.0 / 60.0)
create function to calc latitude and longitude

2024-09-04 08:59 UTC, cepekLP commented on code/func_gps.py
> +        a = math.sin(delta_lat / 2)**2 + math.cos(self.lat_prev) * math.cos(self.lat_current) * math.sin(delta_lon / 2)**2
create function to calc distance from delta lat and long

2024-09-04 08:59 UTC, cepekLP commented on code/func_gps.py
> +def gps_additional_data_live(data_bytes):
remove unused function

2024-09-04 08:59 UTC, cepekLP commented on code/func_gps.py
> +def gps_data_live(data_bytes, filter, lap_timer):
remove unused function

2024-09-04 08:59 UTC, cepekLP commented on code/lap_timer.py
> +            x1: float = 14.7616,
we need to prepare some config file with those values

2024-09-04 08:59 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "name": "cansw1",
cahnge to can_sw1

2024-09-04 09:54 UTC, MalwinaKozak commented on code/data_filtration.py
> +        distance_km = radius_earth_km * c
class moved to func_gps.py

2024-09-09 10:26 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "unit": "°",
change to deg / degrees

2024-09-09 10:26 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "unit": "Bar",
```suggestion
                "unit": "bar",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "unit": "Bar",
```suggestion
                "unit": "bar",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/ecumaster_can_frame_config.json
> +                "unit": "°",
```suggestion
                "unit": "deg",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/telemetry_can_frame_config.json
> +                "unit": "L",
```suggestion
                "unit": "l",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/telemetry_can_frame_config.json
> +                "unit": "",
```suggestion
                "unit": "km/h",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/telemetry_can_frame_config.json
> +                "unit": "",
```suggestion
                "unit": "deg",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/telemetry_can_frame_config.json
> +                "unit": "",
```suggestion
                "unit": "m",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/telemetry_can_frame_config.json
> +                "unit": "B",
```suggestion
                "unit": "bar",
```

2024-09-09 10:26 UTC, cepekLP commented on additional data/telemetry_can_frame_config.json
> +                "unit": "B",
```suggestion
                "unit": "bar",
```

2024-09-09 10:38 UTC, cepekLP approved these changes
🥇

2024-09-09 10:39 UTC, merged