Vss code refactor and add frames sizes in config files
PGRacing/TelemetryGrafana pull request #4
Opened 2024-09-24 20:47 UTC by MalwinaKozak

2024-09-24 21:02 UTC, cepekLP requested changes

2024-09-24 21:02 UTC, cepekLP commented on code/serial/Redis.py
> +                for _ in range(self.can_parser.get_ecumaster_frame_size(id & 0x7ff)):
add frame size to variable
eg size = self.can_parser.get_ecumaster_frame_size(id & 0x7ff)

2024-09-24 21:02 UTC, cepekLP commented on code/serial/Redis.py
> +        self.abs = Vss()
```suggestion
        self.vss = Vss()
```

2024-09-24 21:02 UTC, cepekLP commented on code/sensors/VSS.py
> +    def callback_front(self, dataframe):
remove

2024-09-24 21:10 UTC, MalwinaKozak commented on code/serial/Redis.py
> +        self.can_parser.register_telemetry_callback('0x503', self.vss.callback)
callback deleted

2024-09-25 14:52 UTC, cepekLP approved these changes
🌵

2024-09-25 15:01 UTC, merged